export const actionConstants = {
    SET_FORGOT_PASSWORD : 'SET_FORGOT_PASSWORD',
    SET_LOGINMODALSHOW : 'SET_LOGINMODALSHOW',
    SET_SLIDER_VALUE : 'SET_SLIDER_VALUE',
    SET_TWOFAVERFICATION: 'SET_TWOFAVERFICATION',
    SET_LOGINMODALSTATUS : 'SET_LOGINMODALSTATUS',
    SET_PASSWORDRECOVERY : 'SET_PASSWORDRECOVERY',
    SET_LOGOUTMODAL : 'SET_LOGOUTMODAL',
    SET_TWOFAMODALSTATUS: 'SET_TWOFAMODALSTATUS',
}